### ISSUE TITLE
擴展B-G區字型提議

### ISSUE THREAD

**Issue by Hulenkius** [max32002/max-hana#1]
花園明朝向來以涵蓋CJK著稱，希望您的字型也能擴充爲全字庫！
花園明朝擴展B-F區的字型在HanaMinB中；G區的字形，可以在這個ttf檔中獲取：
https://github.com/jasonvenn/Valuable-Fonts/raw/master/CJKV-ExtG.ttf
希望字型越來越好！

**Comment by max32002** [comment]
感謝你的反應，但是如何把超過 65535 字打包進一個字體檔，這個技術我目前還沒學會。

**Comment by Hulenkius** [comment]
> 感謝你的反應，但是如何把超過 65535 字打包進一個字體檔，這個技術我目前還學會。

一個ttf檔的字形限制就是65535…所以必須使用多個字型檔。不過，G區字形可以合到HanaMinA中，並不超過限度。

**Comment by max32002** [comment]
已合併。
